"""baseline

Revision ID: 0a0a59b228cc
Revises: 
Create Date: 2026-07-02 13:57:33.059605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # ScriptVox: autogenerate emits sqlmodel.sql.sqltypes.AutoString(...)
                 # for every String/Optional[str] column but never imports the
                 # module itself (known Alembic+SQLModel gap) — always import it
                 # here so generated migrations don't NameError on their own types.


# revision identifiers, used by Alembic.
revision: str = '0a0a59b228cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preferred_tts_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'ANALYZED', 'GENERATING', 'DONE', 'FAILED', name='bookstatus'), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('audio_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mp3_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cover_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tts_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('genre', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_status'), 'book', ['status'], unique=False)
    op.create_table('voice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voice_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sa.Enum('CATALOGUE', 'CLONED', name='voicekind'), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'NEUTRAL', 'UNKNOWN', name='gender'), nullable=True),
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('reference_audio_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_voice_id'), 'voice', ['voice_id'], unique=True)
    op.create_table('chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'GENERATING', 'DONE', 'FAILED', name='chapterstatus'), nullable=False),
    sa.Column('audio_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'position')
    )
    op.create_index(op.f('ix_chapter_book_id'), 'chapter', ['book_id'], unique=False)
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'NEUTRAL', 'UNKNOWN', name='gender'), nullable=False),
    sa.Column('age_category', sa.Enum('CHILD', 'YOUNG_ADULT', 'ADULT', 'ELDER', 'UNKNOWN', name='agecategory'), nullable=False),
    sa.Column('tone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('voice_quality', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('voice_tone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('voice_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'name')
    )
    op.create_index(op.f('ix_character_book_id'), 'character', ['book_id'], unique=False)
    op.create_table('character_merge_suggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('survivor_character_id', sa.Integer(), nullable=False),
    sa.Column('merged_character_id', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='mergesuggestionstatus'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['merged_character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['survivor_character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_merge_suggestion_book_id'), 'character_merge_suggestion', ['book_id'], unique=False)
    op.create_table('segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('segment_type', sa.Enum('NARRATION', 'DIALOGUE', name='segmenttype'), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('emotion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('audio_offset_ms', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_id', 'position')
    )
    op.create_index(op.f('ix_segment_chapter_id'), 'segment', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_segment_character_id'), 'segment', ['character_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_segment_character_id'), table_name='segment')
    op.drop_index(op.f('ix_segment_chapter_id'), table_name='segment')
    op.drop_table('segment')
    op.drop_index(op.f('ix_character_merge_suggestion_book_id'), table_name='character_merge_suggestion')
    op.drop_table('character_merge_suggestion')
    op.drop_index(op.f('ix_character_book_id'), table_name='character')
    op.drop_table('character')
    op.drop_index(op.f('ix_chapter_book_id'), table_name='chapter')
    op.drop_table('chapter')
    op.drop_index(op.f('ix_voice_voice_id'), table_name='voice')
    op.drop_table('voice')
    op.drop_index(op.f('ix_book_status'), table_name='book')
    op.drop_table('book')
    op.drop_table('app_setting')
    # ### end Alembic commands ###
