"""add failed_stage to book

Revision ID: 67521bdee0e5
Revises: 29e226c24b2d
Create Date: 2026-07-11 21:11:09.519361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # ScriptVox: autogenerate emits sqlmodel.sql.sqltypes.AutoString(...)
                 # for every String/Optional[str] column but never imports the
                 # module itself (known Alembic+SQLModel gap) — always import it
                 # here so generated migrations don't NameError on their own types.


# revision identifiers, used by Alembic.
revision: str = '67521bdee0e5'
down_revision: Union[str, Sequence[str], None] = '29e226c24b2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('failed_stage', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'failed_stage')
    # ### end Alembic commands ###
