"""add segment_take table

Revision ID: 730790d05e4d
Revises: d52310d77db1
Create Date: 2026-07-18 23:56:07.326435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # ScriptVox: autogenerate emits sqlmodel.sql.sqltypes.AutoString(...)
                 # for every String/Optional[str] column but never imports the
                 # module itself (known Alembic+SQLModel gap) — always import it
                 # here so generated migrations don't NameError on their own types.


# revision identifiers, used by Alembic.
revision: str = '730790d05e4d'
down_revision: Union[str, Sequence[str], None] = 'd52310d77db1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segment_take',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('audio_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('voice_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('emotion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['segment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segment_take_segment_id'), 'segment_take', ['segment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_segment_take_segment_id'), table_name='segment_take')
    op.drop_table('segment_take')
    # ### end Alembic commands ###
