"""add queued_at to chapter

Revision ID: db9016b64888
Revises: 67521bdee0e5
Create Date: 2026-07-12 06:21:15.944578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # ScriptVox: autogenerate emits sqlmodel.sql.sqltypes.AutoString(...)
                 # for every String/Optional[str] column but never imports the
                 # module itself (known Alembic+SQLModel gap) — always import it
                 # here so generated migrations don't NameError on their own types.


# revision identifiers, used by Alembic.
revision: str = 'db9016b64888'
down_revision: Union[str, Sequence[str], None] = '67521bdee0e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('queued_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapter', 'queued_at')
    # ### end Alembic commands ###
